# Specify the HTCondor Universe (vanilla is the default and is used
universe = docker
docker_image=aflatoxing/maker3
#
#
# Specify your executable (single binary or a script that runs several
executable = busco.sh
arguments = $(name)
output = $(name)_busco.out
log = $(name)_busco.log
error = $(name)_busco.err
#
# Specify that HTCondor should transfer files to and from the
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = 
#transfer_output_files = 
#
#Tell HTCondor what amount of compute resources
request_cpus = 1
request_memory = 10GB
request_disk = 10GB
#
queue name from new_names.txt
